### ISSUE TITLE
Remove link to wiki?

### ISSUE THREAD

**Issue by oibind** [FarsetLabs/farsetlabs.github.io#184]
The [wiki ](http://wiki.farsetlabs.org.uk/) service seems to be down. When was it last used? Does it still serve a purpose?

**Comment by andrewbolster** [comment]
Well, the wiki's not actually *down*, it's just not there; has lived at farsetlabs.org.uk/wiki/ for a few years, but also hasn't been *changed* in that length of time. 

Unless there are any objections I'd be inclined to accept this and then if/when the wiki gets actual use again, to reinstate with the right link. 

@Stealthii ?
