### ISSUE TITLE
Dependabot Setup

### ISSUE THREAD

**Issue by andrewbolster** [FarsetLabs/farsetlabs.github.io#195]
During the resolution of #193, @oibind suggested using dependabot to automagically keep the bundle dependencies up to date. 

I'm not sure on how we'd be able to automatically test any potentially breaking upstream changes, but it's a good idea!

**Comment by maxwell-k** [comment]
Dependabot is [proprietary](https://github.com/dependabot/dependabot-core#license)
- not open source, while [Renovatebot](https://github.com/renovatebot/renovate) is AGPL-3.0 and offers comparable features. Would you consider a PR using renovatebot?

**Comment by awflwafl** [comment]
Dependabot's been acquired by GitHub with the plan to build it in to GitHub completely. I'll turn it on.
