### ISSUE TITLE
The "Get in touch" contact links on About resolve to a 404.

### ISSUE THREAD

**Issue by oibind** [FarsetLabs/farsetlabs.github.io#199]
![image](https://user-images.githubusercontent.com/25280584/55310633-de016780-5458-11e9-9563-ac302545bc19.png)
![image](https://user-images.githubusercontent.com/25280584/55310755-2caf0180-5459-11e9-9dd0-0be552d37cc2.png)

**Comment by andrewbolster** [comment]
@Stealthii killed the discourse as part of server migration. In theory it's a short term outage.
