### ISSUE TITLE
slackin.farsetlabs.org.uk SSL error

### ISSUE THREAD

**Issue by chris18890** [FarsetLabs/farsetlabs.github.io#217]
when browsing to https://slackin.farsetlabs.org.uk, user recieves an SSL ewrror, firefox text below

"
Web sites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for slackin.farsetlabs.org.uk. The certificate is only valid for the following names: *.herokuapp.com, herokuapp.com
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN
"

http://slackin.farsetlabs.org.uk works as expected

**Comment by awflwafl** [comment]
@chris18890 Cheers for opening the issue.

The below might be useful for whoever looks into addressing this.

---

### [SSL Endpoint](https://devcenter.heroku.com/articles/ssl-endpoint)

> To enable SSL on a custom domain, for example, www.example.com, use the SSL Endpoint add-on.
> 
> SSL Endpoint is a paid add-on service. Please keep this in mind when provisioning the service.

**Comment by chris18890** [comment]
@awflwafl AFAIK this is still an issue, even thoguh we've removed the public link on the website.

**Comment by chris18890** [comment]
Closing as no longer relevant, resolved indirectly by #345
