### ISSUE TITLE
Colon is missing before the list of membership types on the Membership Benefits page.

### ISSUE THREAD

**Issue by oibind** [FarsetLabs/farsetlabs.github.io#240]
![image](https://user-images.githubusercontent.com/25280584/78991955-1b033e00-7b32-11ea-95e1-d5d4ac88090d.png)

**Comment by andrewbolster** [comment]
Ok, this is really weird because it was in the original HTML version but somehow didn't make it across.... https://github.com/FarsetLabs/farsetlabs.github.io/commit/4891c68e5fbc6624e1a22ec340bce15a8e0405cc
