### ISSUE TITLE
http://www.farsetlabs.org.uk/about/net_conf.html out of date

### ISSUE THREAD

**Issue by chris18890** [FarsetLabs/farsetlabs.github.io#25]
The DNS section of http://www.farsetlabs.org.uk/about/net_conf.html could do with being updated

Should http://www.farsetlabs.org.uk/about/net_conf.html exist on the site as is? Should it be moved into the wiki, or the will the network config info that's on both the the MDWIki & MediaWiki sites, be migrated to the main website?

**Comment by andrewbolster** [comment]
@Stealthii I can't see anything too wrong so this may be closable.

@chris18890 justification for leaving this on the main page is the same as for keeping the rules etc; make sure any changes are verified and recorded.

**Comment by andrewbolster** [comment]
Ref #130
