### ISSUE TITLE
Add "Edit this Page on GitHub" to Each Page

### ISSUE THREAD

**Issue by awflwafl** [FarsetLabs/farsetlabs.github.io#267]
I saw a plugin for this. It's going to make it way easier for people to contribute on the go, especially if they're not that familiar with Jekyll.

**Comment by oibind** [comment]
Was this [jekyll-admin](https://github.com/jekyll/jekyll-admin)?

**Comment by awflwafl** [comment]
@oibind it's [github-metadata](https://github.com/jekyll/github-metadata). We get it for free as a [github-pages dependency](https://pages.github.com/versions/).
