### ISSUE TITLE
HDL not reader friendly

### ISSUE THREAD

**Issue by Dylan1312** [FarsetLabs/farsetlabs.github.io#29]
HDL has a bunch of legalese that makes it dififcult for a user to understand what the hell it is. A more user friendly version of how HDL works needs created and the bits unrelated to actually labelling an item should be hidden under T&C or the like.

**Comment by andrewbolster** [comment]
Believe the changes mad as part of AD-73 / 28cab2e5f81605df634fad3a6759bc74637bb8f0 where the HDL and other policies were summarised onto the [Rules and Policies](http://www.farsetlabs.org.uk/about/rules_and_policies.html) page
