### ISSUE TITLE
Dead link to JIRA on rules page

### ISSUE THREAD

**Issue by chris18890** [FarsetLabs/farsetlabs.github.io#310]
On https://www.farsetlabs.org.uk/about/rules_and_policies.html the issue tracker link points to https://jira.farsetlabs.org.uk/, I'm thinking this should be changed instead to point to ~https://github.com/FarsetLabs/somebody-should~ https://trello.com/b/E0E5a6YA/farset-labs-public

**Comment by awflwafl** [comment]
Sounds good, we'll also need to integrate https://github.com/FarsetLabs/somebody-should into Slack. Should be dozble through the GitHub app we've already got set up in Slack.

We'll 100% forget about it otherwise.

**Comment by chris18890** [comment]
Link should be pointed towards trello if SomebodyShould is no longer a thing

**Comment by chris18890** [comment]
No longer relevant due to a323c0ae57cd924a6a55f7d0cbb5d220ddfcc2eb
