### ISSUE TITLE
Menu icon (button) not showing on mobile screensize

### ISSUE THREAD

**Issue by O4FDev** [FarsetLabs/farsetlabs.github.io#411]
![Screenshot 2024-03-05 at 21 40 17](https://github.com/FarsetLabs/farsetlabs.github.io/assets/52675277/ccf72fda-9550-4054-980c-c525090adc5c)

Can be replicated using an iOS Simulator through XCode, or by using safari on your desktop, scaling it down to mobile size, or by opening farsetlabs.org.uk on safari mobile.

**Comment by alistairjcbrown** [comment]
This doesn't appear to be Safari specific -- the issue can be replicated on Firefox and Chrome

**Comment by O4FDev** [comment]
As it turns out there isn't an icon either! 
![Screenshot 2024-03-05 at 21 50 33](https://github.com/FarsetLabs/farsetlabs.github.io/assets/52675277/351b791a-c49a-46e6-a5c4-c5c06140d5f9)
