### ISSUE TITLE
Memberships no longer match blog

### ISSUE THREAD

**Issue by andrewbolster** [FarsetLabs/farsetlabs.github.io#57]
After the "New year new Farset" blog post, which announced changes to the membership system that I assume were suitably ratified, the membership options listed in the membership page no longer match those presented in the blog post.

**Comment by Stealthii** [comment]
:-1:

**Comment by chris18890** [comment]
when it says in the blog post "Details can be found on the website" I assume that means the membership page, & if so, should the post be edited to have a link?
