### ISSUE TITLE
Officers should have their own page

### ISSUE THREAD

**Issue by andrewbolster** [FarsetLabs/farsetlabs.github.io#93]
I think it would make sense to split the officers section in the about page  (directors / nems) off to a separate page. 

I don't want to call it "about us", to me "officers" makes most sense but I'm open to other suggestions.

**Comment by mhazley** [comment]
As a slight aside that would include stuff like this - I have proposed a storyboarding session to start to work on site improvements and overhaul, this is one thing I wanted to address.

**Comment by awflwafl** [comment]
The NIDevConf website has a "Team" section, which might be a good name.
